spring:
  datasource:
    url: jdbc:postgresql://${PG_DB_HOST:localhost}:${PG_DB_PORT:5432}/${PG_DB_USERNAME:game}?currentSchema=${PG_DB_NAME:public}
    username: ${PG_DB_USERNAME:postgres}
    password: ${PG_DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: ${PG_DB_NAME:public}
    change-log: classpath:db/changelog/liquibase-master.yaml
    enabled: true