name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: List files in the repository
        run: ls -la  # Шаг для проверки содержимого

      - name: Build Docker images
        run: |
          echo "Building Docker images..."
          docker-compose -f docker-compose.yaml build

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images
        run: |
          docker tag docker-spring-boot-postgres:latest diperweb/docker-spring-boot-postgres:latest
          docker push diperweb/docker-spring-boot-postgres:latest

      - name: Run Docker Compose
        run: |
          echo "Starting services with Docker Compose..."
          docker-compose -f docker-compose.yaml up -d
